[build]
ignore = "false"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache"

[[edge_functions]]
path = "/proxy/ecb/*"
function = "ecb_proxy"

[[edge_functions]]
path = "/proxy/investing_com/*"
function = "investing_com_proxy"

[context.production.environment]
ECB_HOSTNAME = "tobcalc.com/proxy/ecb"
INVESTING_COM_HOSTNAME = "tobcalc.com/proxy/investing_com"

[context.dev.environment]
ECB_HOSTNAME = "dev.tobcalc.com/proxy/ecb"
INVESTING_COM_HOSTNAME = "dev.tobcalc.com/proxy/investing_com"
