[build]
ignore = "false"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache"

[[edge_functions]]
path = "/proxy/ecb/*"
function = "ecb_proxy"

[[edge_functions]]
path = "/proxy/investing_com/*"
function = "investing_com_proxy"
