[build]
ignore = "false"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache"

[[edge_functions]]
path = "/proxy/ecb/*"
function = "ecb_proxy"

[[edge_functions]]
path = "/proxy/yahoo_finance/*"
function = "yahoo_finance_proxy"

[[edge_functions]]
path = "/proxy/yahoo_finance_query1/*"
function = "yahoo_finance_query1_proxy"

[[redirects]]
from = "/guide-ibkr"
to = "https://github.com/samjmck/tobcalc/blob/master/docs/brokers/interactive-brokers-guide.md"
status = 302

[[redirects]]
from = "/guide-degiro"
to = "https://github.com/samjmck/tobcalc/blob/master/docs/brokers/degiro-guide.md"
status = 302

[context.production.environment]
ECB_HOSTNAME = "tobcalc.com/proxy/ecb"
YAHOO_FINANCE_HOSTNAME = "tobcalc.com/proxy/yahoo_finance"
YAHOO_FINANCE_QUERY1_HOSTNAME = "tobcalc.com/proxy/yahoo_finance_query1"

[context.staging.environment]
ECB_HOSTNAME = "staging.tobcalc.com/proxy/ecb"
YAHOO_FINANCE_HOSTNAME = "staging.tobcalc.com/proxy/yahoo_finance"
YAHOO_FINANCE_QUERY1_HOSTNAME = "staging.tobcalc.com/proxy/yahoo_finance_query1"

[context.dev.environment]
ECB_HOSTNAME = "dev.tobcalc.com/proxy/ecb"
YAHOO_FINANCE_HOSTNAME = "dev.tobcalc.com/proxy/yahoo_finance"
YAHOO_FINANCE_QUERY1_HOSTNAME = "dev.tobcalc.com/proxy/yahoo_finance_query1"
