name: deno-tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.17.1
      - run: deno test --allow-read --allow-net src/{,**/}*_test.ts
